import type { DashboardPayload, SrePayload } from "./types";

export const sampleDashboardPayload: DashboardPayload = {
  generatedAt: "2026-05-10T10:00:00Z",
  projects: [
    {
      id: "dukefarm-production",
      name: "DukeFarm Production",
      environment: "Production",
      owner: "DukeFarm Operations",
      server: {
        hostname: "dukefarm-prod-01",
        os: "Ubuntu 22.04 LTS",
        access: "Public HTTPS ingest",
        reverseProxy: "Nginx",
        processManager: "PM2",
      },
      endpoints: [
        {
          name: "DukeFarm API",
          url: "http://127.0.0.1:4000/healthz",
          statusCode: 200,
          latencyMs: 178,
          checkedAt: "2026-05-10T09:59:30Z",
        },
        {
          name: "DukeFarm API v1",
          url: "http://127.0.0.1:4000/api/v1/health",
          statusCode: 200,
          latencyMs: 226,
          checkedAt: "2026-05-10T09:59:30Z",
        },
        {
          name: "DukeFarm API",
          url: "http://127.0.0.1:4000/healthz",
          statusCode: 503,
          latencyMs: 940,
          checkedAt: "2026-05-10T09:59:30Z",
        },
      ],
      processes: [
        {
          name: "dukefarm-admin",
          role: "Admin dashboard",
          status: "online",
          cpuPercent: 9,
          memoryMb: 132,
          restarts: 0,
          uptimeSeconds: 65_000,
        },
        {
          name: "dukefarm-backend",
          role: "Express API",
          status: "errored",
          cpuPercent: 18,
          memoryMb: 184,
          restarts: 5,
          uptimeSeconds: 74_000,
        },
        {
          name: "opspulse-agent",
          role: "Telemetry sender",
          status: "online",
          cpuPercent: 4,
          memoryMb: 64,
          restarts: 0,
          uptimeSeconds: 320,
        },
      ],
      metrics: {
        cpuPercent: 71,
        memoryPercent: 78,
        diskPercent: 68,
        networkInMbps: 12.4,
        networkOutMbps: 5.8,
      },
      alerts: [
        {
          id: "alert-backend-down",
          severity: "critical",
          title: "dukefarm-backend process is down",
          message: "PM2 reports dukefarm-backend as errored and API health returns 503.",
          createdAt: "2026-05-10T09:59:31Z",
          acknowledged: false,
        },
        {
          id: "alert-memory",
          severity: "warning",
          title: "memory pressure above baseline",
          message: "Host memory crossed 75% for the last collection window.",
          createdAt: "2026-05-10T09:53:00Z",
          acknowledged: false,
        },
      ],
      timeline: [
        { at: "09:42", healthScore: 94, latencyMs: 118 },
        { at: "09:45", healthScore: 92, latencyMs: 126 },
        { at: "09:48", healthScore: 88, latencyMs: 172 },
        { at: "09:51", healthScore: 81, latencyMs: 214 },
        { at: "09:54", healthScore: 78, latencyMs: 226 },
        { at: "09:57", healthScore: 61, latencyMs: 480 },
        { at: "10:00", healthScore: 42, latencyMs: 940 },
      ],
    },
  ],
};

export const sampleSrePayload: SrePayload = {
  dashboard: sampleDashboardPayload,
  incidents: [
    {
      id: "inc-backend-down",
      projectId: "dukefarm-production",
      fingerprint: "dukefarm-production:process-dukefarm-backend",
      severity: "critical",
      title: "DukeFarm backend process is down",
      summary: "PM2 reports dukefarm-backend as errored and /healthz returns 503.",
      status: "open",
      startedAt: "2026-05-10T09:59:31Z",
      lastSeenAt: "2026-05-10T10:00:00Z",
      rootCauseHint: "Backend process likely down",
      occurrences: 2,
    },
    {
      id: "inc-memory-pressure",
      projectId: "dukefarm-production",
      fingerprint: "dukefarm-production:memory",
      severity: "warning",
      title: "Memory pressure above baseline",
      summary: "Host memory crossed 75% in the last collection window.",
      status: "acknowledged",
      startedAt: "2026-05-10T09:53:00Z",
      lastSeenAt: "2026-05-10T10:00:00Z",
      rootCauseHint: "Possible memory pressure restart loop",
      occurrences: 4,
      acknowledgedAt: "2026-05-10T09:55:00Z",
    },
  ],
  agents: [
    {
      projectId: "dukefarm-production",
      isStale: false,
      lastSeenAt: "2026-05-10T10:00:00Z",
      agent: {
        version: "1.0.0",
        hostname: "dukefarm-prod-01",
        os: "Ubuntu 22.04 LTS",
        pm2Version: "5.4.2",
        receivedAt: "2026-05-10T10:00:00Z",
      },
      driftIssues: [
        {
          kind: "missingExpectedProcess",
          message: "Expected process 'dukefarm-frontend' was not reported by PM2.",
        },
      ],
    },
  ],
  commands: [
    {
      id: "cmd-health-demo",
      projectId: "dukefarm-production",
      action: "healthCheckNow",
      target: "dukefarm-production",
      status: "succeeded",
      requestedBy: "portfolio-user",
      requestedAt: "2026-05-10T10:01:00Z",
      claimedAt: "2026-05-10T10:01:05Z",
      finishedAt: "2026-05-10T10:01:08Z",
      summary: "Health checks passed.",
    },
    {
      id: "cmd-redeploy-demo",
      projectId: "dukefarm-production",
      action: "redeployBackend",
      target: "dukefarm-backend",
      status: "pending",
      requestedBy: "portfolio-user",
      requestedAt: "2026-05-10T10:03:00Z",
      summary: "Waiting for opspulse-agent to claim command.",
    },
  ],
  slo: {
    projectId: "dukefarm-production",
    targetAvailabilityPercent: 99.9,
    availabilityPercent: 98.62,
    errorBudgetBurnedPercent: 1380,
    endpoints: [
      {
        name: "DukeFarm API",
        url: "http://127.0.0.1:4000/healthz",
        availabilityPercent: 98.62,
        p95LatencyMs: 480,
        p99LatencyMs: 940,
        totalChecks: 72,
        failedChecks: 1,
      },
    ],
  },
};
